### Ebay
GET http://localhost:5000/searchEbay?articulo=ryzen 3600

### Olx
GET http://localhost:5000/searchOlx?articulo=laptop hp 


### Mercado libre 
Get http://localhost:5000/search?url=https://articulo.mercadolibre.com.ec/MEC-430509150-samsung-a11-a12-a21s-a31-a71-a32-a52-a72-_JM#c_id=/home/category/deal-items/element&c_uid=33a6fac2-6cab-40a5-a900-b78de859c787


### Mercado libre sin modal
Get  http://localhost:5000/search?url=https://articulo.mercadolibre.com.ec/MEC-430351261-tarjeta-de-video-nvidia-gtx-1060-3gb-msi-gaming-x-_JM#reco_item_pos=3&reco_backend=item_decorator&reco_backend_type=function&reco_client=home_navigation-history&reco_id=325b9292-ba54-4dea-82a3-2fcfc20a3085&c_id=/home/navigation/element&c_uid=645641a0-b9a9-4f14-92d6-2a0c21a8bb63

### Mercado libre sin usuario
Get  http://localhost:5000/search?url=https://articulo.mercadolibre.com.ec/MEC-429816773-computador-gamer-combo-completo-_JM#position=5&type=item&tracking_id=b218982b-b1cb-4d36-9e34-2d0e029beea7