### Ebay
GET http://localhost:5000/searchEbay?articulo=Tarjeta De Video Nvidia Gtx 1060 3gb Msi Gaming X


### Olx
GET http://localhost:5000/searchOlx?articulo=laptop hp 


### Mercado libre 
Get http://localhost:5000/search?url= 